# Generated by Django 3.1.5 on 2021-03-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_friendly_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
