# Generated by Django 3.1.5 on 2021-03-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('opening_statement', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True, max_length=50)),
                ('availability', models.BooleanField(choices=[(True, 'Available'), (False, 'Unavailable')], default=True)),
                ('contact_number', models.PositiveIntegerField()),
                ('PT_image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
