# Generated by Django 3.1.5 on 2021-03-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt',
            name='contact_number',
            field=models.CharField(max_length=12),
        ),
    ]
