# Generated by Django 3.1.5 on 2021-03-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0002_auto_20210319_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt',
            name='full_name',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
