# Generated by Django 3.1.5 on 2021-03-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0003_auto_20210319_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pt',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
