# Generated by Django 3.1.5 on 2021-02-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210215_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
