# Generated by Django 3.1.5 on 2021-02-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Servings',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5),
        ),
    ]
