# Generated by Django 3.1.5 on 2021-03-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210223_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Brand',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='Size',
            field=models.CharField(max_length=100),
        ),
    ]
