# Generated by Django 3.1.5 on 2021-03-24 20:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210324_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Flavor',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None),
        ),
    ]
